# Generated by Django 4.0.1 on 2022-02-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='items', to='auctions.Category'),
        ),
    ]
